### ISSUE TITLE
Change icon or text color

### ISSUE THREAD

**Issue by G-Luz** [SplashByte/animated_toggle_switch#22]
I using the widget with texts, don't used icon, but how I can change my selected text color? Or check current index selected?

I did not find this possibility in the documentation.

If I just set the color in my AppText component, your prop will change the text color of the selected and unselected index and I don't want that, I just need to change the color of the currently selected index

My source code:

``` 

  String currentFilterValue = '';
  List<String> listValues = ['Meus', 'Todos'];

  @override
  void initState() {
    super.initState();
    currentFilterValue = widget.isAllContactsFilter ? 'Todos' : 'Meus';
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedToggleSwitch<String>.size(
      textDirection: TextDirection.rtl,
      current: currentFilterValue,
      values: listValues,
      borderRadius: BorderRadius.circular(6),
      indicatorSize: const Size.fromWidth(35),
      height: 30,
      customIconBuilder: (context, local, global) {
        return Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            AppText(
              text: local.value,
              fontSize: 10,
              fontWeight: FontWeight.w700,
            ),
          ],
        );
      },
      indicatorColor: Colors.white,
      colorBuilder: (i) {
        return AppColors.mainRed;
      },
      borderColor: Colors.transparent,
      onChanged: (i) {
        setState(() => currentFilterValue = i);
        widget.onChangeCallback(i);
      },
    );
  }

``` 

My toggle component: 

![Captura de tela de 2022-04-27 09-04-39](https://user-images.githubusercontent.com/58195699/165514313-1ac06a65-892d-4f14-a205-26075fe2376c.png)
![Captura de tela de 2022-04-27 09-05-23](https://user-images.githubusercontent.com/58195699/165514405-5209a7a7-a67c-439e-838c-2a77aa36f95d.png)

**Comment by MaddinMade** [comment]
I am sorry for the poor documentation. You can't find everything you need so quickly. Probably I should expand the README. Is the following working for you?
```
AppText(
    text: local.value,
    fontSize: 10,
    fontWeight: FontWeight.w700,
    color: Color.lerp(<standardColor>, <selectedColor>, local.animationValue),
),
```

**Comment by MaddinMade** [comment]
If you want to control the colors completely, you have to disable the animated opacity, you can use `iconOpacity: 1`.

**Comment by G-Luz** [comment]
Sorry for my inattention, maybe I made a mistake due to the naming and my own use of the plugin :sweat_smile:
Working with iconOpacity and Color.lerp works fine for me.

The documentation is very good for work with icons :+1:
Thanks for the plugin and your answer :smiley: :wave:

**Comment by MaddinMade** [comment]
@G-Luz That was not your fault. The parameters are relatively tricky. 😅
There is nothing wrong with using text with the Switch. I do that myself as well. But you have to give some name to the parameters and I have chosen icon. 🤷
No problem, I'm glad I could help.
