### ISSUE TITLE
translation example

### ISSUE THREAD

**Issue by thorizer** [SplashByte/animated_toggle_switch#25]
is it possible to add the translation example to the list ? many thanks

https://user-images.githubusercontent.com/13587810/193271947-6da24338-4b65-4583-bad1-9286c6cc8d4e.mp4

not sure how you added the inner padding between the icons and the switch itself

**Comment by MaddinMade** [comment]
I originally didn't want to include the example because it uses a third-party package. But if you want to implement the example, feel free to follow the code in #23.

**Comment by MaddinMade** [comment]
@thorizer Can this issue be closed?

**Comment by thorizer** [comment]
yes, thanks a lot
