### ISSUE TITLE
foreground icon and background icon do mismatch by a few pixel

### ISSUE THREAD

**Issue by LuNiPriSe** [SplashByte/animated_toggle_switch#26]
I am trying to create a switch with transparent backgrounds. But I noticed that the icons do not overlap perfectly. You can see 1 or 2 pixel of the background icon shine through.

Solutions:
- perfect overlap
- hide background icon when foreground is "above it" (would also allow for different sizes)
- parameters to "shift" foreground icon 

<img width="110" alt="Screenshot 2022-10-13 at 05 18 57" src="https://user-images.githubusercontent.com/84306/195492374-3b1adab4-8a38-43ac-a775-bb6da403e058.png">
<img width="112" alt="Screenshot 2022-10-13 at 05 17 47" src="https://user-images.githubusercontent.com/84306/195492377-82ac65c8-95dc-47e3-8d77-4e1c78b7d273.png">
<img width="103" alt="Screenshot 2022-10-13 at 05 17 23" src="https://user-images.githubusercontent.com/84306/195492379-a737aad6-5921-4e8a-8dd6-e7d1581bfd3c.png">
<img width="116" alt="Screenshot 2022-10-13 at 05 16 57" src="https://user-images.githubusercontent.com/84306/195492380-70257c35-dc95-4ec1-999a-bb1060cd72fb.png">
<img width="114" alt="Screenshot 2022-10-13 at 05 16 41" src="https://user-images.githubusercontent.com/84306/195492381-dc4dc0b9-5115-4197-91d3-8369cb629030.png">

**Comment by MaddinMade** [comment]
Thanks for opening the issue :)

Can you provide code to reproduce the problem? I haven't looked at the problem yet, but maybe the only way to solve this problem is to hide the background icon when the foreground icon is over it. Such a small inaccuracy can also be a problem with the Flutter framework.
