### ISSUE TITLE
onchanged property always remains false

### ISSUE THREAD

**Issue by santosh81066** [SplashByte/animated_toggle_switch#27]
hello sir the value in on change property is false Always whether my current value is true or false  the value in on change is not changing according to my current state

**Comment by MaddinMade** [comment]
I apologize for the late reply.
When exactly is the wrong value passed into onChanged? Can you provide a reproducible example?
onChanged is basically only called when the user changes the value and not when the state changes.

**Comment by santosh81066** [comment]
```
 AnimatedToggleSwitch<bool>.dual(
                current:false
                first: false,
                second: true,
                dif: 50.0,
                borderColor: Colors.transparent,
                borderWidth: 5.0,
                height: 55,
                boxShadow: const [
                  BoxShadow(
                    color: Colors.black26,
                    spreadRadius: 1,
                    blurRadius: 2,
                    offset: Offset(0, 1.5),
                  ),
                ],
                onChanged: (b) => setState(() => positive = b),
                colorBuilder: (b) => b ? Colors.red : Colors.green,
                iconBuilder: (value) => value
                    ? Icon(Icons.coronavirus_rounded)
                    : Icon(Icons.tag_faces_rounded),
                textBuilder: (value) => value
                    ? Center(child: Text('Oh no...'))
                    : Center(child: Text('Nice :)')),
              ),
```
in thie above code current is false so I expect b in onchange should be false while I change the switch it should be true but on change returns false while changing the switch

**Comment by MaddinMade** [comment]
I have taken this code and always get back true when changing the switch. I do not see the error.

**Comment by santosh81066** [comment]
by changing the switch it is changing to true but if my current value is true then I expect false on changing not true

**Comment by MaddinMade** [comment]
Yes, but with your code above, your current value is never `true` because you explicitly inserted `false` for `current`.

**Comment by santosh81066** [comment]
just change the current value to true and print value in on change eg..print(b) in this situation I expect output as false

**Comment by MaddinMade** [comment]
I'm really sorry, but I've tried both now: With `value: false` it always returns true in onChange and with `value: true` it always returns false in `onChange`. I can't reconstruct or understand the problem.

**Comment by santosh81066** [comment]
ok i will check again
