### ISSUE TITLE
Ability to initialize with null/unselected value

### ISSUE THREAD

**Issue by talski** [splashbyte/animated_toggle_switch#31]
Currently, if I initialize the widget with a null value in `current` property, it will throw an error `Index out of range`, It would be nice if the provided value is not in the `values` property, it init properly but with no option selected.

**Comment by MaddinMade** [comment]
Thanks for the feature request :)
So do you want no value to be selected if it is not in the list, or only if it is null?

**Comment by talski** [comment]
for my needs, a `null` value is enough, could be only if the generics allows it `<int?>`, maybe an error state (border/background color) when it's not in `values` range instead of throwing an error?

**Comment by MaddinMade** [comment]
I think it makes more sense to throw an error because it's not something that's supposed to happen. But I'm thinking about how best to implement the fact that no value is selected, since this feature has been requested several times now.

**Comment by maeddin** [comment]
@olsonjb @talski I would appreciate it if you could take a look at my current approach to this issue. On [unselected_value](https://github.com/splashbyte/animated_toggle_switch/tree/unselected_value) these changes are implemented and an example of how to use the feature. For using it in your projects, you can use the following lines in your `pubspec.yaml`:

```
animated_toggle_switch:
  git:
    url: https://github.com/splashbyte/animated_toggle_switch.git
    ref: unselected_value
```

**Comment by maeddin** [comment]
I have now updated the branch to the probably final version. Now values for `current` are allowed, which are not in `values`, as you suggested @talski.
