### ISSUE TITLE
[Feature request] Add the possibility to toggle off the switch

### ISSUE THREAD

**Issue by OroshiX** [splashbyte/animated_toggle_switch#41]
### Context
With `allowUnlistedValues: true`, we can now have initial value = null, and it means the switch doesn't have anything selected initially. But it's missing a use case: how to unselect the toggle (without adding an intermediate state of null when we only change from value1 to value 2)?

### Use case
I tried to use the `AnimatedToggleSwitch` with the following use case: clicking on the already selected value switches off the toggle (unselects everything). But I only want to change my state to null when I click on the already selected value. 

### What I tried
I tried to have the `onChanged` callback deal with this, but the `onChanged` callback is only called when the value is not the one we have currently selected. Then I tried with `onTap` callback, but because it doesn't have the currently selected value available, I cannot add a check for `myValue != null`. This is what I tried:
```dart
onChanged: (changed) { // this doesn't get triggered when the value has not changed
  setState(() => myValue = changed);
},
onTap: () {
  if (myValue != null) { // I cannot check what I have tapped, so this is the best I could do
    setState(() => myValue = null);
  }
}
```
### Result/issue
If I tap on the same value as selected, then it's working correctly (because `myValue` was selected, and it's now unselected). But if I tap on another value, the `onTap` is triggered, then the `onChanged` is triggered, so I get the intermediary state `myValue==null` that messes up my state.

### Summary
To sum up what I want to achieve VS what I get:
```mermaid
flowchart TB
  subgraph What I want
    direction TB
    U("value = null");
    U -->|"Click on 'A'"| A(value = A)
    A -->|"Click on 'A'"|U
    A -->|"Click on 'B'"| B("value = B")
  end
  subgraph What I get
    direction TB
    u("value = null");
    u -->|"Click on 'A'"| a(value = A)
    a -->|"Click on 'A'"| u
    a -->|"Click on 'B'"| b1("value = null\n(I want to get rid of this state)")
    b1 -->|"Then"|b2("value = B")
  end
```
### Feature request
So my feature request would be:
* either have the `onChanged` callback be triggered even when the value has not changed,
* or have a new callback for "toggling off" the value when `allowUnlistedValues == true`
* or even, have a parameter to the callback `onTap` to get what we value are currently tapping on

Please tell me if this is unclear.

**Comment by maeddin** [comment]
Thanks for the feature request. I will change the onTap method to pass a parameter. I'll comment again once I've implemented a first prototype of the feature.
Do you have any additional suggestions on what else to pass in this parameter besides the tapped value and index?

**Comment by maeddin** [comment]
@OroshiX Could you take a look at my implementation of this feature? I would appreciate any feedback on this :)

**Comment by OroshiX** [comment]
Hey @maeddin , thanks for your quick reply and action. I had a look, and it is very nice! Also, you added some more info in this `TapInfo` class that could definitely be useful. 👍

_A comment on naming_: I had a bit of a struggle understanding that `current` was actually referring to the previous value before tapping, because as I see it, the `TapInfo` refers to the tap action, so the word "current" would be IMO more about where we tapped right now. I would replace `current` (and `currentIndex`) with `previous` (and `previousIndex`). But this might be only my opinion 🙂 

Other than this nitpick, the change seems good, and as a bonus, I could do exactly what I wanted to do, with limited changes to my code, so thank you very much 💪

**Comment by maeddin** [comment]
Thanks for the detailed feedback 🙂

Yes, the naming of `current` can be confusing, but `previous` is also not true because on a tap, `onChanged` is not necessarily triggered and changes the value. I will think again how to name this best. Otherwise I can also remove `current`, so it doesn't lead to confusion.

**Comment by OroshiX** [comment]
Maybe `beforeTap` (and `beforeTapIndex`) instead? It doesn't seem to imply a change on the value 🤔
Removing `current` would also be fine by me, no strong opinion on my side.

**Comment by maeddin** [comment]
I removed `current` and `currentIndex` from `TapInfo`, because I don't know any practical use case for these values in `TapInfo`. 
However, `beforeTap` and `beforeTapIndex` are good name suggestions that I may include in a later release.

Thanks for the help. You created this issue at just the right time that the changes could still be added to version 0.8 🙂

**Comment by maeddin** [comment]
@OroshiX I have changed the parameters for `onTap` a little bit. Is the new structure still somewhat understandable?
Sorry to bother you, but I need an opinion apart from my own 😅

**Comment by OroshiX** [comment]
The `position` field of `TapInfo` could benefit from a comment on possible range for the values it could take: if we are tapping slightly on the left of 1st element, is it = to -1, or to 0 or -0.2? Or maybe the tapInfo is null? (same question for tapping on the right of last element)

Apart from that, the new structure is still understandable in my opinion.
