### ISSUE TITLE
Option to execute custom code after completion of animation

### ISSUE THREAD

**Issue by BaseD-75** [splashbyte/animated_toggle_switch#50]
All info on the desired functionality can be found here: [https://github.com/splashbyte/animated_toggle_switch/discussions/49](url)

In short: OnChange gives an option to execute code immediately after a change. It would be great if there was an option that gets triggerd after completion of the animation.

**Comment by BaseD-75** [comment]
Hi there, looks like you added a new option. Great!! 

I tried to find some documentation on this, so I can try it. I am probably overlooking it somehow. Could you point me in the right direction?

**Comment by maeddin** [comment]
@BaseD-75 You can now listen to the current position of the indicator in the `positionListener`. So you only have to check if the indicator is already at the desired position and then you can execute your code. If this does not work as desired, I can also introduce a separate function for this. I look forward to your feedback :)
