### ISSUE TITLE
indicatorSize can't be changed

### ISSUE THREAD

**Issue by wangcheng319** [splashbyte/animated_toggle_switch#52]
AnimatedToggleSwitch<bool>.dual(
              current: logic.state.switchState,
              first: false,
              second: true,
              spacing: 0,
              indicatorSize: Size(100, 40.h),)

AnimatedToggleSwitch<bool>.dual(
              current: logic.state.switchState,
              first: false,
              second: true,
              spacing: 0,
              indicatorSize: Size(200, 40.h),)

**Comment by wangcheng319** [comment]
AnimatedToggleSwitch<bool>.dual(
              current: logic.state.switchState,
              first: false,
              second: true,
              spacing: 0,
              indicatorSize: Size(158.w, 70.h),
              animationDuration: const Duration(milliseconds: 300),
              style: const ToggleStyle(
                borderColor: Colors.transparent,
                indicatorColor: Colors.transparent,
                backgroundColor: Colors.white,
              ),
              customStyleBuilder: (context, local, global) {
                if (global.position <= 0.0) {
                  return const ToggleStyle(backgroundColor: Color(0xffDCD8E8));
                }
                return ToggleStyle(
                    backgroundGradient: LinearGradient(
                  colors: const [Color(0xffFFBA1A), Color(0xffDCD8E8)],
                  stops: [
                    global.position - (1 - 2 * max(0, global.position - 0.5)) * 0.7,
                    global.position + max(0, 2 * (global.position - 0.5)) * 0.7,
                  ],
                ));
              },
              borderWidth: 0.0,
              height: 90.0.h,
              onChanged: (b) {
                logic.state.switchState = b;
                logic.update();
                widget.onSwitch.call(b);
                if (b) {
                  if (rAnimationTime != null) {
                    rAnimationTime?.cancel();
                  }
                  startLAnimationTime();
                } else {
                  if (lAnimationTime != null) {
                    lAnimationTime?.cancel();
                  }
                  startRAnimationTime();
                }
              },
              iconBuilder: (value) => value ? _buildSwitchIconItem('STOP', Icons.power_settings_new_rounded) : _buildSwitchIconItem('START', Icons.power_settings_new_rounded),
              textBuilder: (value) => value ? _buildArrowWidget(true, logic) : _buildArrowWidget(false, logic)),

**Comment by maeddin** [comment]
If I adjust the `indicatorSize` everything works. I need a reproducible example to be able to check this issue.
