### ISSUE TITLE
Indicator boxShadow is clipped

### ISSUE THREAD

**Issue by flodaniel** [splashbyte/animated_toggle_switch#56]
In this example i want the indicator to have a boxShadow without the entire toggle having a shadow. Right now this boxShadow is clipped. The plugin should expose an option to prevent clipping. 

![image](https://github.com/splashbyte/animated_toggle_switch/assets/6661557/1ff4584a-ea88-47df-be2c-1b7ffee6c27e)

**Comment by maeddin** [comment]
I'll take a look at it today :) Thanks for reporting this issue.

**Comment by flodaniel** [comment]
Wonderful, this works! 🚀

**Comment by maeddin** [comment]
Thanks :) The new version is now available on [pub.dev](https://pub.dev/packages/animated_toggle_switch).
